#!/usr/bin/env bash
#
# Generate the Homebrew formula for the `caniac` (codeanalyzer-iac) binary.
#
# This is the non-Rust equivalent of what cargo-dist does automatically: it takes
# the per-platform binaries that the release already publishes as GitHub Release
# assets, computes their sha256, and emits a formula that downloads + installs the
# matching binary for the user's platform.
#
# It reads the binaries straight from the release-bins/ dir built by release.yml,
# so the checksums are guaranteed to match the bytes that were uploaded. The
# download URLs point at the GitHub Release assets of the SAME tag.
#
# Usage:
#   REPO=codellm-devkit/codeanalyzer-iac VERSION=0.2.0 \
#     ./generate_formula.sh ../../release-bins > codeanalyzer-iac.rb
#
set -euo pipefail

BINS_DIR="${1:?usage: generate_formula.sh <release-bins-dir>}"
REPO="${REPO:?set REPO, e.g. codellm-devkit/codeanalyzer-iac}"
VERSION="${VERSION:?set VERSION, e.g. 0.2.0}"
BASE_URL="https://github.com/${REPO}/releases/download/v${VERSION}"

# shasum on macOS, sha256sum on the Linux runner; both print "<digest>  <file>".
sha() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | cut -d' ' -f1
  else
    sha256sum "$1" | cut -d' ' -f1
  fi
}

# Map each release asset (named by Python wheel platform tag) to its Homebrew
# os/arch block. Windows is intentionally omitted -- Homebrew is macOS/Linux only.
asset_macos_arm="caniac-macosx_11_0_arm64"
asset_macos_intel="caniac-macosx_11_0_x86_64"
asset_linux_intel="caniac-manylinux_2_17_x86_64"
asset_linux_arm="caniac-manylinux_2_17_aarch64"

for a in "$asset_macos_arm" "$asset_macos_intel" "$asset_linux_intel" "$asset_linux_arm"; do
  [[ -f "$BINS_DIR/$a" ]] || { echo "missing expected binary: $BINS_DIR/$a" >&2; exit 1; }
done

cat <<FORMULA
# This file is auto-generated by packaging/homebrew/generate_formula.sh on release.
# Do not edit by hand -- changes will be overwritten on the next tag.
class CodeanalyzerIac < Formula
  desc "CLDK infrastructure-as-code analyzer (caniac) -- emits canonical CLDK analysis.json"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${BASE_URL}/${asset_macos_arm}"
      sha256 "$(sha "$BINS_DIR/$asset_macos_arm")"
    end
    on_intel do
      url "${BASE_URL}/${asset_macos_intel}"
      sha256 "$(sha "$BINS_DIR/$asset_macos_intel")"
    end
  end

  on_linux do
    on_arm do
      url "${BASE_URL}/${asset_linux_arm}"
      sha256 "$(sha "$BINS_DIR/$asset_linux_arm")"
    end
    on_intel do
      url "${BASE_URL}/${asset_linux_intel}"
      sha256 "$(sha "$BINS_DIR/$asset_linux_intel")"
    end
  end

  def install
    # The release asset is a bare executable; Homebrew stages it under its
    # original (platform-tagged) name. Install it as the canonical "caniac".
    bin.install Dir["caniac-*"].first => "caniac"
  end

  test do
    # caniac --version prints "caniac version <v>", the same string it stamps on
    # analyzer.version in every analysis document.
    assert_match "caniac version #{version}", shell_output("#{bin}/caniac --version")
  end
end
FORMULA
